import type { GetStaticProps } from 'next'
import { FC } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { WPPost } from '../libs/wpapi/interfaces'
import Link from 'next/link'

export const Home:FC<{
  posts: WPPost[]
}> = ({posts}) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.jsとWordpressを使ったHeadlessCMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next.jsとWordpressを使ったHeadlessCMS</h1>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <div className={styles.grid}>
          {posts.map((post, index) => 
            <Link href={`/post/${post.id}`}>
              <a key={index}  href="" className={styles.card}>
                <h2>{post.title.rendered}</h2>
                <p>{post.content.rendered}</p>
              </a>
            </Link>
          )}
        </div>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps<{}> = async () => {
  const res = await fetch('http://wordpress/wp-json/wp/v2/posts')
  const posts: WPPost[] = await res.json()
  
  return { props: { posts } };
}

export default Home
